# See https://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region - The
# default region below is for CloudFront WAF creation. For ALB WAF we need to
# set it from inventory
- include_tasks: "{{ stage|default('create') }}_waf.yml"
  with_items: "{{ waf_regions|default(['us-east-1']) }}"
  loop_control:
    loop_var: task_item
