- name: create WAF conditions
  aws_waf_condition:
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    filters: "{{ item.filters }}"
    purge_filters: yes
    state: present
    profile: "{{ profile|default(omit) }}"
  with_items: "{{ waf_conditions }}"

- name: create WAF rules
  aws_waf_rule:
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    conditions: "{{ item.filters }}"
    purge_conditions: yes
    state: present
    profile: "{{ profile|default(omit) }}"
  with_items: "{{ waf_rules }}"

- name: create WAF Web ACL
  aws_waf_web_acl:
    name: "{{ waf_web_acl.name }}"
    rules: "{{ waf_web_acl.rules }}"
    purge_rules: yes
    state: present
    profile: "{{ profile|default(omit) }}"
    default_action: "{{ waf_web_acl.default_action }}"
